version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR
  install:
    runtime-versions: 
      nodejs: 16
    commands: 
      - echo Installing Deps
      - yarn install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
      - echo Build Image started on `date`
      - echo Building the Docker image....
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 612000474429.dkr.ecr.us-east-1.amazonaws.com
      - docker build -t usde-server:latest
      - docker tag usde-server:latest 612000474429.dkr.ecr.us-east-1.amazonaws.com/usde-server:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker Image
      - docker push 612000474429.dkr.ecr.us-east-1.amazonaws.com/usde-server:latest


